[package]
name = "dfuse_capi"
version = "0.1.0"
authors = ["Samuel Dolt <samuel@dolt.ch>"]

[dependencies]
dfuse = {  path = "../" }


[lib]
crate-type = ["cdylib", "staticlib"]

[profile.release]
lto = true
panic = 'abort'

[profile.dev]
panic = 'abort'
